export interface AchievementDef {
  slug: string;
  name: string;
  desc: string;
  icon: string;
  category: string;
  difficulty: number;
  progressTarget?: number;
  progressKey?: string;
  progressLabel?: string;
}

export const ACHIEVEMENTS: AchievementDef[] = [
  // ── Beginner ─────────────────────────────────────────────────────────────
  {
    slug: "first_step",
    name: "First Step",
    desc: "Complete your first run.",
    icon: "🏃",
    category: "Beginner",
    difficulty: 1,
    progressTarget: 1,
    progressKey: "completed_runs",
    progressLabel: "runs completed",
  },
  {
    slug: "social_starter",
    name: "Social Starter",
    desc: "Join your first public run.",
    icon: "🤝",
    category: "Beginner",
    difficulty: 1,
    progressTarget: 1,
    progressKey: "public_runs_joined",
    progressLabel: "public runs joined",
  },
  {
    slug: "host_in_making",
    name: "Host in the Making",
    desc: "Host your first run.",
    icon: "🎯",
    category: "Beginner",
    difficulty: 1,
    progressTarget: 1,
    progressKey: "hosted_runs",
    progressLabel: "runs hosted",
  },
  {
    slug: "connected",
    name: "Connected",
    desc: "Add your first friend.",
    icon: "👥",
    category: "Beginner",
    difficulty: 1,
    progressTarget: 1,
    progressKey: "friends_count",
    progressLabel: "friends added",
  },
  // ── Getting Moving ────────────────────────────────────────────────────────
  {
    slug: "five_alive",
    name: "5 & Alive",
    desc: "Complete 5 total runs.",
    icon: "⭐",
    category: "Consistency",
    difficulty: 2,
    progressTarget: 5,
    progressKey: "completed_runs",
    progressLabel: "runs completed",
  },
  {
    slug: "squad_runner",
    name: "Squad Runner",
    desc: "Join a run with 3 or more participants.",
    icon: "👟",
    category: "Social",
    difficulty: 2,
    progressTarget: 1,
    progressKey: "squad_runs_count",
    progressLabel: "squad runs",
  },
  {
    slug: "miles_25",
    name: "25 Mile Mark",
    desc: "Reach 25 total miles.",
    icon: "📍",
    category: "Mileage",
    difficulty: 2,
    progressTarget: 25,
    progressKey: "total_miles",
    progressLabel: "miles logged",
  },
  // ── Building Habit ────────────────────────────────────────────────────────
  {
    slug: "ten_toes_down",
    name: "Ten Toes Down",
    desc: "Complete 10 runs.",
    icon: "💪",
    category: "Consistency",
    difficulty: 3,
    progressTarget: 10,
    progressKey: "completed_runs",
    progressLabel: "runs completed",
  },
  {
    slug: "monthly_grinder",
    name: "Monthly Grinder",
    desc: "Complete 8 runs in one month.",
    icon: "📆",
    category: "Consistency",
    difficulty: 3,
    progressTarget: 8,
    progressKey: "monthly_max_runs",
    progressLabel: "runs in best month",
  },
  {
    slug: "half_marathon",
    name: "Half Marathon Hero",
    desc: "Complete a 13.1 mile run.",
    icon: "🏅",
    category: "Mileage",
    difficulty: 3,
    progressTarget: 131,
    progressKey: "max_single_run_miles_x10",
    progressLabel: "miles in best run (×10)",
  },
  {
    slug: "crew_builder",
    name: "Crew Builder",
    desc: "Host 5 runs.",
    icon: "🎪",
    category: "Social",
    difficulty: 3,
    progressTarget: 5,
    progressKey: "hosted_runs",
    progressLabel: "runs hosted",
  },
  // ── Going Far ─────────────────────────────────────────────────────────────
  {
    slug: "miles_100",
    name: "Century Club",
    desc: "Reach 100 total miles.",
    icon: "💯",
    category: "Mileage",
    difficulty: 4,
    progressTarget: 100,
    progressKey: "total_miles",
    progressLabel: "miles logged",
  },
  {
    slug: "streak_week",
    name: "Streak Week",
    desc: "Run 3 days in a row.",
    icon: "🔥",
    category: "Consistency",
    difficulty: 4,
    progressTarget: 3,
    progressKey: "max_streak_days",
    progressLabel: "day streak",
  },
  {
    slug: "night_owl",
    name: "Night Owl",
    desc: "Complete 5 runs after 8 PM.",
    icon: "🌙",
    category: "Lifestyle",
    difficulty: 4,
    progressTarget: 5,
    progressKey: "night_runs_count",
    progressLabel: "night runs",
  },
  {
    slug: "community_leader",
    name: "Community Leader",
    desc: "Host 20 total participants across all runs.",
    icon: "🏆",
    category: "Social",
    difficulty: 4,
    progressTarget: 20,
    progressKey: "participants_hosted_total",
    progressLabel: "participants hosted",
  },
  // ── Elite ─────────────────────────────────────────────────────────────────
  {
    slug: "marathoner",
    name: "Marathoner",
    desc: "Complete a 26.2 mile run.",
    icon: "🎽",
    category: "Mileage",
    difficulty: 5,
    progressTarget: 262,
    progressKey: "max_single_run_miles_x10",
    progressLabel: "miles in best run (×10)",
  },
  {
    slug: "morning_warrior",
    name: "Morning Warrior",
    desc: "Complete 10 runs before 7 AM.",
    icon: "☀️",
    category: "Lifestyle",
    difficulty: 5,
    progressTarget: 10,
    progressKey: "morning_runs_count",
    progressLabel: "morning runs",
  },
  {
    slug: "two_week_lock_in",
    name: "Two Week Lock-In",
    desc: "Run 10 days within any 14-day window.",
    icon: "🔒",
    category: "Consistency",
    difficulty: 5,
    progressTarget: 10,
    progressKey: "max_runs_in_14_days",
    progressLabel: "runs in best 14-day window",
  },
  {
    slug: "miles_250",
    name: "250 Strong",
    desc: "Reach 250 total miles.",
    icon: "🌟",
    category: "Mileage",
    difficulty: 5,
    progressTarget: 250,
    progressKey: "total_miles",
    progressLabel: "miles logged",
  },
  {
    slug: "speedster",
    name: "Speedster",
    desc: "Run a sub-7:00/mi pace (minimum 1 mile).",
    icon: "⚡",
    category: "Speed",
    difficulty: 5,
    progressTarget: 1,
    progressKey: "has_sub7_pace",
    progressLabel: "sub-7 runs",
  },
  // ── Legend ────────────────────────────────────────────────────────────────
  {
    slug: "explorer",
    name: "Explorer",
    desc: "Run in 5 different locations.",
    icon: "🗺️",
    category: "Lifestyle",
    difficulty: 6,
    progressTarget: 5,
    progressKey: "unique_locations",
    progressLabel: "unique locations",
  },
  {
    slug: "comeback_kid",
    name: "Comeback Kid",
    desc: "Return to running after 30 days off.",
    icon: "💫",
    category: "Lifestyle",
    difficulty: 6,
    progressTarget: 1,
    progressKey: "had_comeback",
    progressLabel: "comebacks",
  },
  {
    slug: "negative_split",
    name: "Negative Split",
    desc: "Finish the second half of a run faster than the first.",
    icon: "↗️",
    category: "Speed",
    difficulty: 6,
    progressTarget: 1,
    progressKey: "negative_split_count",
    progressLabel: "negative splits",
  },
  {
    slug: "five_k_crusher",
    name: "5K Crusher",
    desc: "Complete a 5K run under your target pace.",
    icon: "🎯",
    category: "Speed",
    difficulty: 6,
    progressTarget: 1,
    progressKey: "five_k_crusher_count",
    progressLabel: "5K crushed",
  },
  {
    slug: "pace_perfect",
    name: "Pace Perfect",
    desc: "Match the advertised run pace within ±10 seconds.",
    icon: "✅",
    category: "Speed",
    difficulty: 6,
    progressTarget: 1,
    progressKey: "pace_perfect_count",
    progressLabel: "pace-perfect runs",
  },
];

export const ACHIEVEMENT_CATEGORIES = [
  "Beginner",
  "Consistency",
  "Mileage",
  "Social",
  "Speed",
  "Lifestyle",
];
