export interface AchievementDef {
  slug: string;
  name: string;
  desc: string;
  icon: string;
  category: string;
  difficulty: number;
  activityType: "run" | "ride" | "general";
  progressTarget?: number;
  progressKey?: string;
  progressLabel?: string;
}

export const ACHIEVEMENTS: AchievementDef[] = [
  // ── Run: Beginner ─────────────────────────────────────────────────────────
  {
    slug: "first_step",
    name: "First Step",
    desc: "Complete your first run.",
    icon: "🏃",
    category: "Beginner",
    difficulty: 1,
    activityType: "run",
    progressTarget: 1,
    progressKey: "completed_runs",
    progressLabel: "runs completed",
  },
  {
    slug: "social_starter",
    name: "Social Starter",
    desc: "Join your first public run.",
    icon: "🤝",
    category: "Beginner",
    difficulty: 1,
    activityType: "run",
    progressTarget: 1,
    progressKey: "public_runs_joined",
    progressLabel: "public runs joined",
  },
  {
    slug: "host_in_making",
    name: "Host in the Making",
    desc: "Host your first run.",
    icon: "🎯",
    category: "Beginner",
    difficulty: 1,
    activityType: "run",
    progressTarget: 1,
    progressKey: "hosted_runs",
    progressLabel: "runs hosted",
  },
  // ── General ───────────────────────────────────────────────────────────────
  {
    slug: "connected",
    name: "Connected",
    desc: "Add your first friend.",
    icon: "👥",
    category: "Beginner",
    difficulty: 1,
    activityType: "general",
    progressTarget: 1,
    progressKey: "friends_count",
    progressLabel: "friends added",
  },
  // ── Run: Consistency ──────────────────────────────────────────────────────
  {
    slug: "five_alive",
    name: "5 & Alive",
    desc: "Complete 5 total runs.",
    icon: "⭐",
    category: "Consistency",
    difficulty: 2,
    activityType: "run",
    progressTarget: 5,
    progressKey: "completed_runs",
    progressLabel: "runs completed",
  },
  {
    slug: "squad_runner",
    name: "Squad Runner",
    desc: "Join a run with 3 or more participants.",
    icon: "👟",
    category: "Social",
    difficulty: 2,
    activityType: "run",
    progressTarget: 1,
    progressKey: "squad_runs_count",
    progressLabel: "squad runs",
  },
  {
    slug: "miles_25",
    name: "25 Mile Mark",
    desc: "Reach 25 total miles.",
    icon: "📍",
    category: "Mileage",
    difficulty: 2,
    activityType: "run",
    progressTarget: 25,
    progressKey: "total_miles",
    progressLabel: "miles logged",
  },
  {
    slug: "ten_toes_down",
    name: "Ten Toes Down",
    desc: "Complete 10 runs.",
    icon: "💪",
    category: "Consistency",
    difficulty: 3,
    activityType: "run",
    progressTarget: 10,
    progressKey: "completed_runs",
    progressLabel: "runs completed",
  },
  {
    slug: "monthly_grinder",
    name: "Monthly Grinder",
    desc: "Complete 8 runs in one month.",
    icon: "📆",
    category: "Consistency",
    difficulty: 3,
    activityType: "run",
    progressTarget: 8,
    progressKey: "monthly_max_runs",
    progressLabel: "runs in best month",
  },
  {
    slug: "half_marathon",
    name: "Half Marathon Hero",
    desc: "Complete a 13.1 mile run.",
    icon: "🏅",
    category: "Mileage",
    difficulty: 3,
    activityType: "run",
    progressTarget: 131,
    progressKey: "max_single_run_miles_x10",
    progressLabel: "miles in best run (×10)",
  },
  {
    slug: "crew_builder",
    name: "Crew Builder",
    desc: "Host 5 runs.",
    icon: "🎪",
    category: "Social",
    difficulty: 3,
    activityType: "run",
    progressTarget: 5,
    progressKey: "hosted_runs",
    progressLabel: "runs hosted",
  },
  {
    slug: "miles_100",
    name: "Century Club",
    desc: "Reach 100 total miles.",
    icon: "💯",
    category: "Mileage",
    difficulty: 4,
    activityType: "run",
    progressTarget: 100,
    progressKey: "total_miles",
    progressLabel: "miles logged",
  },
  {
    slug: "streak_week",
    name: "Streak Week",
    desc: "Run 3 days in a row.",
    icon: "🔥",
    category: "Consistency",
    difficulty: 4,
    activityType: "run",
    progressTarget: 3,
    progressKey: "max_streak_days",
    progressLabel: "day streak",
  },
  {
    slug: "night_owl",
    name: "Night Owl",
    desc: "Complete 5 runs after 8 PM.",
    icon: "🌙",
    category: "Lifestyle",
    difficulty: 4,
    activityType: "run",
    progressTarget: 5,
    progressKey: "night_runs_count",
    progressLabel: "night runs",
  },
  {
    slug: "community_leader",
    name: "Community Leader",
    desc: "Host 20 total participants across all runs.",
    icon: "🏆",
    category: "Social",
    difficulty: 4,
    activityType: "run",
    progressTarget: 20,
    progressKey: "participants_hosted_total",
    progressLabel: "participants hosted",
  },
  {
    slug: "marathoner",
    name: "Marathoner",
    desc: "Complete a 26.2 mile run.",
    icon: "🎽",
    category: "Mileage",
    difficulty: 5,
    activityType: "run",
    progressTarget: 262,
    progressKey: "max_single_run_miles_x10",
    progressLabel: "miles in best run (×10)",
  },
  {
    slug: "morning_warrior",
    name: "Morning Warrior",
    desc: "Complete 10 runs before 7 AM.",
    icon: "☀️",
    category: "Lifestyle",
    difficulty: 5,
    activityType: "run",
    progressTarget: 10,
    progressKey: "morning_runs_count",
    progressLabel: "morning runs",
  },
  {
    slug: "two_week_lock_in",
    name: "Two Week Lock-In",
    desc: "Run 10 days within any 14-day window.",
    icon: "🔒",
    category: "Consistency",
    difficulty: 5,
    activityType: "run",
    progressTarget: 10,
    progressKey: "max_runs_in_14_days",
    progressLabel: "runs in best 14-day window",
  },
  {
    slug: "miles_250",
    name: "250 Strong",
    desc: "Reach 250 total miles.",
    icon: "🌟",
    category: "Mileage",
    difficulty: 5,
    activityType: "run",
    progressTarget: 250,
    progressKey: "total_miles",
    progressLabel: "miles logged",
  },
  {
    slug: "speedster",
    name: "Speedster",
    desc: "Run a sub-7:00/mi pace (minimum 1 mile).",
    icon: "⚡",
    category: "Speed",
    difficulty: 5,
    activityType: "run",
    progressTarget: 1,
    progressKey: "has_sub7_pace",
    progressLabel: "sub-7 runs",
  },
  {
    slug: "explorer",
    name: "Explorer",
    desc: "Run in 5 different locations.",
    icon: "🗺️",
    category: "Lifestyle",
    difficulty: 6,
    activityType: "run",
    progressTarget: 5,
    progressKey: "unique_locations",
    progressLabel: "unique locations",
  },
  {
    slug: "comeback_kid",
    name: "Comeback Kid",
    desc: "Return to running after 30 days off.",
    icon: "💫",
    category: "Lifestyle",
    difficulty: 6,
    activityType: "run",
    progressTarget: 1,
    progressKey: "had_comeback",
    progressLabel: "comebacks",
  },
  {
    slug: "negative_split",
    name: "Negative Split",
    desc: "Finish the second half of a run faster than the first.",
    icon: "↗️",
    category: "Speed",
    difficulty: 6,
    activityType: "run",
    progressTarget: 1,
    progressKey: "negative_split_count",
    progressLabel: "negative splits",
  },
  {
    slug: "five_k_crusher",
    name: "5K Crusher",
    desc: "Complete a 5K run under your target pace.",
    icon: "🎯",
    category: "Speed",
    difficulty: 6,
    activityType: "run",
    progressTarget: 1,
    progressKey: "five_k_crusher_count",
    progressLabel: "5K crushed",
  },
  {
    slug: "pace_perfect",
    name: "Pace Perfect",
    desc: "Match the advertised run pace within ±10 seconds.",
    icon: "✅",
    category: "Speed",
    difficulty: 6,
    activityType: "run",
    progressTarget: 1,
    progressKey: "pace_perfect_count",
    progressLabel: "pace-perfect runs",
  },

  // ── Ride: Beginner ────────────────────────────────────────────────────────
  {
    slug: "first_ride",
    name: "First Ride",
    desc: "Complete your first group ride.",
    icon: "🚴",
    category: "Beginner",
    difficulty: 1,
    activityType: "ride",
    progressTarget: 1,
    progressKey: "completed_rides",
    progressLabel: "rides completed",
  },
  {
    slug: "social_cyclist",
    name: "Social Cyclist",
    desc: "Join your first public ride.",
    icon: "🤸",
    category: "Beginner",
    difficulty: 1,
    activityType: "ride",
    progressTarget: 1,
    progressKey: "public_rides_joined",
    progressLabel: "public rides joined",
  },
  {
    slug: "ride_host_debut",
    name: "Ride Host Debut",
    desc: "Host your first ride.",
    icon: "🏁",
    category: "Beginner",
    difficulty: 1,
    activityType: "ride",
    progressTarget: 1,
    progressKey: "ride_hosted_count",
    progressLabel: "rides hosted",
  },
  // ── Ride: Getting Rolling ─────────────────────────────────────────────────
  {
    slug: "five_rides",
    name: "5 & Rolling",
    desc: "Complete 5 rides.",
    icon: "⭐",
    category: "Consistency",
    difficulty: 2,
    activityType: "ride",
    progressTarget: 5,
    progressKey: "completed_rides",
    progressLabel: "rides completed",
  },
  {
    slug: "ride_miles_25",
    name: "25 Ride Miles",
    desc: "Reach 25 total miles on rides.",
    icon: "📍",
    category: "Mileage",
    difficulty: 2,
    activityType: "ride",
    progressTarget: 25,
    progressKey: "ride_total_miles",
    progressLabel: "ride miles logged",
  },
  {
    slug: "squad_rider",
    name: "Squad Rider",
    desc: "Join a ride with 3 or more participants.",
    icon: "🚵",
    category: "Social",
    difficulty: 2,
    activityType: "ride",
    progressTarget: 1,
    progressKey: "squad_rides_count",
    progressLabel: "squad rides",
  },
  // ── Ride: Building Habit ──────────────────────────────────────────────────
  {
    slug: "ten_rides",
    name: "Ten Rides Deep",
    desc: "Complete 10 rides.",
    icon: "💪",
    category: "Consistency",
    difficulty: 3,
    activityType: "ride",
    progressTarget: 10,
    progressKey: "completed_rides",
    progressLabel: "rides completed",
  },
  {
    slug: "monthly_rider",
    name: "Monthly Rider",
    desc: "Complete 8 rides in one month.",
    icon: "📆",
    category: "Consistency",
    difficulty: 3,
    activityType: "ride",
    progressTarget: 8,
    progressKey: "ride_monthly_max",
    progressLabel: "rides in best month",
  },
  {
    slug: "half_century",
    name: "Half Century",
    desc: "Complete a 50-mile ride.",
    icon: "🏅",
    category: "Mileage",
    difficulty: 3,
    activityType: "ride",
    progressTarget: 50,
    progressKey: "ride_max_single_miles",
    progressLabel: "miles in best ride",
  },
  {
    slug: "ride_crew_builder",
    name: "Ride Organizer",
    desc: "Host 5 rides.",
    icon: "🎪",
    category: "Social",
    difficulty: 3,
    activityType: "ride",
    progressTarget: 5,
    progressKey: "ride_hosted_count",
    progressLabel: "rides hosted",
  },
  // ── Ride: Going Far ───────────────────────────────────────────────────────
  {
    slug: "ride_miles_100",
    name: "Century Rider",
    desc: "Reach 100 total miles on rides.",
    icon: "💯",
    category: "Mileage",
    difficulty: 4,
    activityType: "ride",
    progressTarget: 100,
    progressKey: "ride_total_miles",
    progressLabel: "ride miles logged",
  },
  {
    slug: "ride_streak_week",
    name: "Ride Streak",
    desc: "Ride 3 days in a row.",
    icon: "🔥",
    category: "Consistency",
    difficulty: 4,
    activityType: "ride",
    progressTarget: 3,
    progressKey: "ride_max_streak_days",
    progressLabel: "day ride streak",
  },
  {
    slug: "night_rider",
    name: "Night Rider",
    desc: "Complete 5 rides after 8 PM.",
    icon: "🌙",
    category: "Lifestyle",
    difficulty: 4,
    activityType: "ride",
    progressTarget: 5,
    progressKey: "night_rides_count",
    progressLabel: "night rides",
  },
  {
    slug: "ride_community_leader",
    name: "Ride Leader",
    desc: "Host 20 participants across all rides.",
    icon: "🏆",
    category: "Social",
    difficulty: 4,
    activityType: "ride",
    progressTarget: 20,
    progressKey: "ride_participants_hosted",
    progressLabel: "ride participants hosted",
  },
  // ── Ride: Elite ───────────────────────────────────────────────────────────
  {
    slug: "ride_miles_250",
    name: "250 Ride Miles",
    desc: "Reach 250 total miles on rides.",
    icon: "🌟",
    category: "Mileage",
    difficulty: 5,
    activityType: "ride",
    progressTarget: 250,
    progressKey: "ride_total_miles",
    progressLabel: "ride miles logged",
  },
  {
    slug: "morning_cyclist",
    name: "Morning Cyclist",
    desc: "Complete 10 rides before 7 AM.",
    icon: "☀️",
    category: "Lifestyle",
    difficulty: 5,
    activityType: "ride",
    progressTarget: 10,
    progressKey: "morning_rides_count",
    progressLabel: "morning rides",
  },
  {
    slug: "ride_two_week_lock_in",
    name: "Locked In (Ride)",
    desc: "Ride 10 days within any 14-day window.",
    icon: "🔒",
    category: "Consistency",
    difficulty: 5,
    activityType: "ride",
    progressTarget: 10,
    progressKey: "ride_max_in_14_days",
    progressLabel: "rides in best 14-day window",
  },
  {
    slug: "speedster_ride",
    name: "Speed Demon",
    desc: "Complete a ride averaging under 20 min/mi pace.",
    icon: "⚡",
    category: "Speed",
    difficulty: 5,
    activityType: "ride",
    progressTarget: 1,
    progressKey: "has_fast_ride",
    progressLabel: "fast rides",
  },
  {
    slug: "ride_grinder",
    name: "Ride Grinder",
    desc: "Complete 25 rides.",
    icon: "🔄",
    category: "Consistency",
    difficulty: 5,
    activityType: "ride",
    progressTarget: 25,
    progressKey: "completed_rides",
    progressLabel: "rides completed",
  },
  // ── Ride: Legend ──────────────────────────────────────────────────────────
  {
    slug: "ride_explorer",
    name: "Ride Explorer",
    desc: "Ride in 5 different locations.",
    icon: "🗺️",
    category: "Lifestyle",
    difficulty: 6,
    activityType: "ride",
    progressTarget: 5,
    progressKey: "ride_unique_locations",
    progressLabel: "unique ride locations",
  },
  {
    slug: "comeback_cyclist",
    name: "Comeback Cyclist",
    desc: "Return to riding after 30 days off.",
    icon: "💫",
    category: "Lifestyle",
    difficulty: 6,
    activityType: "ride",
    progressTarget: 1,
    progressKey: "had_ride_comeback",
    progressLabel: "comebacks",
  },
  {
    slug: "century_ride",
    name: "Century Ride",
    desc: "Complete a 100-mile ride.",
    icon: "🎽",
    category: "Mileage",
    difficulty: 6,
    activityType: "ride",
    progressTarget: 100,
    progressKey: "ride_max_single_miles",
    progressLabel: "miles in best ride",
  },
  {
    slug: "ride_miles_500",
    name: "500 Ride Miles",
    desc: "Reach 500 total miles on rides.",
    icon: "🌠",
    category: "Mileage",
    difficulty: 6,
    activityType: "ride",
    progressTarget: 500,
    progressKey: "ride_total_miles",
    progressLabel: "ride miles logged",
  },
  {
    slug: "pace_perfect_ride",
    name: "Pace Perfect (Ride)",
    desc: "Match the advertised ride pace within ±10 seconds.",
    icon: "✅",
    category: "Speed",
    difficulty: 6,
    activityType: "ride",
    progressTarget: 1,
    progressKey: "ride_pace_perfect_count",
    progressLabel: "pace-perfect rides",
  },
  // ── Reliability ───────────────────────────────────────────────────────────
  {
    slug: "reliable_50",
    name: "Reliable",
    desc: "Show up to 50% or more of the runs/rides you commit to (min. 5 events).",
    icon: "🟡",
    category: "Reliability",
    difficulty: 2,
    activityType: "general",
    progressTarget: 50,
    progressKey: "attendance_rate_pct",
    progressLabel: "% show-up rate",
  },
  {
    slug: "reliable_65",
    name: "Dependable",
    desc: "Show up to 65% or more of the runs/rides you commit to (min. 5 events).",
    icon: "🔵",
    category: "Reliability",
    difficulty: 3,
    activityType: "general",
    progressTarget: 65,
    progressKey: "attendance_rate_pct",
    progressLabel: "% show-up rate",
  },
  {
    slug: "reliable_80",
    name: "Committed",
    desc: "Show up to 80% or more of the runs/rides you commit to (min. 5 events).",
    icon: "🟢",
    category: "Reliability",
    difficulty: 4,
    activityType: "general",
    progressTarget: 80,
    progressKey: "attendance_rate_pct",
    progressLabel: "% show-up rate",
  },
  {
    slug: "reliable_90",
    name: "Shows Up Every Time",
    desc: "Show up to 90% or more of the runs/rides you commit to (min. 5 events).",
    icon: "⭐",
    category: "Reliability",
    difficulty: 5,
    activityType: "general",
    progressTarget: 90,
    progressKey: "attendance_rate_pct",
    progressLabel: "% show-up rate",
  },
];

export const RUN_ACHIEVEMENTS = ACHIEVEMENTS.filter(
  (a) => a.activityType === "run" || a.activityType === "general"
);

export const RIDE_ACHIEVEMENTS = ACHIEVEMENTS.filter(
  (a) => a.activityType === "ride" || a.activityType === "general"
);

export const ACHIEVEMENT_CATEGORIES = [
  "Beginner",
  "Consistency",
  "Mileage",
  "Social",
  "Speed",
  "Lifestyle",
  "Reliability",
];
